version: 2
jobs:
  build:
    docker:
      - image: "circleci/golang:1.12"

    working_directory: /go/src/github.com/mmmorris1975/aws-secrets-sync
    steps:
      - checkout
      - run: mkdir -p build
      - run: go get -v -t -d ./...
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: go build -v -ldflags '-X main.Version=0.0.1-0-circle' -o build/aws-secrets-sync

      - persist_to_workspace:
          root: build
          paths: aws-secrets-sync

  test:
    docker:
      - image: "circleci/ruby:2.6-stretch"

    steps:
      - checkout

      - attach_workspace:
          at: build

      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: mkdir -p /var/tmp/rspec
      - run:
          command: bundle exec rspec
          when: always

      - store_test_results:
          path: /var/tmp/rspec

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build